# -*- coding: utf-8 -*-
import PyQt5
from PyQt5.QtCore import QSize

import image
# Form implementation generated from reading ui file 'give_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

conn = sqlite3.connect('warehouse.db')


class Ui_Dialog(object):
    def setupUi(self, Dialog, info_good):
        result = {}

        with conn:
            [result.setdefault(i[0], (i[1], i[2], i[3], i[4])) for i in conn.execute(f'SELECT name, description, count, category_id, photo FROM Goods WHERE Goods.name = "{info_good}"')]
            print(result)

        Dialog.setObjectName(info_good)
        Dialog.resize(700, 397)
        Dialog.setStyleSheet("background-image: url(\"OJ91CN0.jpg\");")
        for key, value in result.items():
            self.label = QtWidgets.QLabel(Dialog)
            self.label.setGeometry(QtCore.QRect(50, 50, 281, 41))
            self.label.setStyleSheet("color: #fff;\n"
    "font: 75 12pt \"MS Shell Dlg 2\";")
            self.label.setObjectName("label")
            self.label.setText(f'Товар: {key}')

            self.label = QtWidgets.QLabel(Dialog)
            self.label.setGeometry(QtCore.QRect(50, 100, 1000, 41))
            self.label.setStyleSheet("color: #fff;\n"
                                     "font: 75 12pt \"MS Shell Dlg 2\";")
            self.label.setObjectName("label")
            if value[0] != None:
                self.label.setText(f'Описание: {value[0]}')
            else:
                self.label.setText(f'Описание: отсутствует :(')

            self.label = QtWidgets.QLabel(Dialog)
            self.label.setGeometry(QtCore.QRect(50, 150, 281, 41))
            self.label.setStyleSheet("color: #fff;\n"
                                     "font: 75 12pt \"MS Shell Dlg 2\";")
            self.label.setObjectName("label")
            self.label.setText(f'Количество на складе: {value[1]} шт.')

            self.label = QtWidgets.QLabel(Dialog)
            self.label.setGeometry(QtCore.QRect(200, 0, 281, 41))
            self.label.setStyleSheet("color: #fff;\n"
                                     "font: 75 12pt \"MS Shell Dlg 2\";")
            self.label.setObjectName("label")
            category_name = [i[0] for i in conn.execute(f"SELECT name FROM Category WHERE id = '{value[2]}'")][0]
            self.label.setText(f'Категория: {category_name}')

            self.Image = QtWidgets.QLabel(Dialog)
            self.Image.setGeometry(QtCore.QRect(50, 220, 145, 100))

            self.Image.setPixmap(
                QtGui.QPixmap(
                    f"image/{value[3]}"
                ).scaled(145, 100))


            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Информация о продукте"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
