# -*- coding: utf-8 -*-
import time
from functools import partial
from fuzzywuzzy import fuzz
import PyQt5.QtCore
from PyQt5.QtWidgets import QWidget
from PyQt5.QtCore import QTimer
import information_about_good
import mainwindow as main_window
# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


conn = sqlite3.connect('warehouse.db')

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(775, 460)
        Dialog.setStyleSheet("background-image: url(\"OJ91CN0.jpg\");")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.comboBox.setObjectName("comboBox")

        self.comboBox1 = QtWidgets.QComboBox(Dialog)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 0, 171, 41))
        self.label.setStyleSheet("color: #fff;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(230, 90, 291, 87))
        self.textEdit.setStyleSheet("border:3px solid #ddd;\n"
"font: \"8514oem\";\n"
"background: #fff;\n"
"color: #8cbaff;\n"
"border-radius: 20px;")
        self.textEdit.setObjectName("textEdit")

        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(500, 50, 171, 41))
        self.label1.setStyleSheet("color: #cc3333;\n"
                                 "font: 75 12pt \"MS Shell Dlg 2\";\n"
                                 "")
        self.label1.setObjectName("label")

        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(20, 75, 171, 41))
        self.label2.setStyleSheet("color: #3fcf0a;\n"
                                 "font: 75 12pt \"MS Shell Dlg 2\";\n"
                                 "")
        self.label2.setObjectName("label")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 370, 111, 41))
        self.pushButton_2.setStyleSheet("border-radius: 20px;\n"
"border: 2px solid #fff;\n"
"color: #fff;\n"
"font: 63 9pt \"Yu Gothic UI Semibold\";\n"
"background: #8ccfff;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 370, 111, 41))
        self.pushButton_4.setStyleSheet("border-radius: 20px;\n"
"border: 2px solid #fff;\n"
"color: #fff;\n"
"font: 63 9pt \"Yu Gothic UI Semibold\";\n"
"background: #8ccfff;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 120, 111, 41))
        self.pushButton_5.setStyleSheet("border-radius: 20px;\n"
                                        "border: 2px solid #fff;\n"
                                        "color: #fff;\n"
                                        "font: 63 9pt \"Yu Gothic UI Semibold\";\n"
                                        "background: #8ccfff;")
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(999, 999, 999, 999))
        self.pushButton_6.setStyleSheet("border-radius: 20px;\n"
                                        "border: 2px solid #fff;\n"
                                        "color: #fff;\n"
                                        "font: 63 9pt \"Yu Gothic UI Semibold\";\n"
                                        "background:rgba(0, 0, 0, 0);")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


        with conn:
            for i in [i for i in conn.execute('SELECT name FROM Goods')]:
                print(i)
                self.comboBox.addItem(i[0])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Выберите товар"))
        self.label1.setText(_translate("Dialog", ""))
        self.label2.setText(_translate("Dialog", ""))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\"></span></p></body></html>"))

        self.pushButton_2.setText(_translate("Dialog", "Применить"))
        self.pushButton_4.setText(_translate("Dialog", "Главная"))
        self.pushButton_5.setText(_translate("Dialog", "Найти"))
        self.pushButton_5.clicked.connect(self.search_in_combobox)
        self.pushButton_4.clicked.connect(Dialog.close)
        self.pushButton_2.clicked.connect(partial(self.information_about_good))
        self.pushButton_6.clicked.connect(partial(self.search_goods_info))

    def cursor_def(self):
        print('aaa')

    def search_in_combobox(self):
        self.comboBox1.clear()
        name_good = self.textEdit.toPlainText()
        name = ''
        dict_res = {}
        with conn:
            list_name_good = [i[0] for i in conn.execute('SELECT name FROM Goods')]
            print(list_name_good)
            for i in list_name_good:
                result = fuzz.ratio(i, name_good)
                dict_res[i] = result
            names_combobox_goods = []
            x = 0
            for k, v in dict_res.items():
                if int(v) >= x and int(v)!=0:
                    x = v
                    names_combobox_goods.append(k)
                else:
                    continue
            print(names_combobox_goods)
            if len(names_combobox_goods) != 0:
                self.comboBox1.setGeometry(QtCore.QRect(280, 250, 191, 22))
                self.comboBox1.setObjectName("comboBox")
                self.comboBox1.addItems(names_combobox_goods)
                names_combobox_goods.clear()
                self.pushButton_2.close()

                self.pushButton_6.setGeometry(QtCore.QRect(450, 300, 111, 41))
                self.pushButton_6.setStyleSheet("border-radius: 20px;\n"
                                                "border: 2px solid #fff;\n"
                                                "color: #fff;\n"
                                                "font: 63 9pt \"Yu Gothic UI Semibold\";\n"
                                                "background: #8ccfff;")
                self.pushButton_6.setText('Применить')
                self.pushButton_6.setObjectName("pushButton_6")
                self.pushButton_4.setGeometry(QtCore.QRect(200, 300, 111, 41))

            else:
                pass

        index = self.comboBox.findText(name)
        try:
            if index >= 0:
                self.comboBox.setCurrentIndex(index)
                self.label2.setText('Успешно найден!')
                QTimer.singleShot(3000, lambda: self.label2.setText(''))
            else:
                pass
                with conn:
                    name_by_description = [i[0] for i in conn.execute(f'SELECT name FROM Goods WHERE description = "{name_good}"')][0]
                    name_index = self.comboBox.findText(name_by_description)
                    print(name_by_description)
                    self.comboBox.setCurrentIndex(name_index)
                    self.label2.setText('Успешно найден!')
                    QTimer.singleShot(1500, lambda: self.label2.setText(''))
        except:
            print('Ошибка: товара нет в БД')
            self.label1.setText('Товар не найдет!')
            QTimer.singleShot(2500, lambda: self.label1.setText(''))


    def search_goods_info(self):
        information_about_goods = self.comboBox1.currentText()
        Dialog = QtWidgets.QDialog()
        ui2 = information_about_good.Ui_Dialog()
        ui2.setupUi(Dialog, information_about_goods)
        Dialog.show()
        Dialog.exec_()


    def information_about_good(self):
        info_good = self.comboBox.currentText()
        Dialog = QtWidgets.QDialog()
        ui2 = information_about_good.Ui_Dialog()
        ui2.setupUi(Dialog, info_good)
        Dialog.show()
        Dialog.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
